### ISSUE TITLE
Update min requirements

### ISSUE THREAD

**Issue by timocov** [tradingview/lightweight-charts#745]
- [x] ~Change NodeJS from v12 to v16 (since it's LTS)~ - fixed in #1025
- [x] ~Change build target from es5 to es2016~ - fixed in #1037
- [x] ~Add support for `exports` map~ - fixed #613

**Comment by h0wXD** [comment]
With this you may want to add `npm install --legacy-peer-deps`, so deprecated packages can be installed in v14+, else people will run into errors:

```
lightweight-charts>npm i
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: lightweight-charts@3.3.0
npm ERR! Found: tslint@6.1.3
npm ERR! node_modules/tslint
npm ERR!   dev tslint@"6.1.3" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer tslint@"^5.0.0" from tslint-eslint-rules@5.4.0
npm ERR! node_modules/tslint-eslint-rules
npm ERR!   dev tslint-eslint-rules@"~5.4.0" from the root project

**Comment by timocov** [comment]
> With this you may want to add npm install --legacy-peer-deps, so deprecated packages can be installed in v14+, else people will run into errors:

@h0wXD It looks like support for npm@7, not for nodejs v14 (by default nodejs v14 includes npm@6 which works fine at the moment - `Latest LTS Version: 14.17.0 (includes npm 6.14.13)` from https://nodejs.org/en/download/).

**Comment by EugeneMeles** [comment]
> ```
> npm ERR! Could not resolve dependency:
> npm ERR! peer tslint@"^5.0.0" from tslint-eslint-rules@5.4.0
> npm ERR! node_modules/tslint-eslint-rules
> npm ERR!   dev tslint-eslint-rules@"~5.4.0" from the root project
> ```

Yeap, problem with dependency in `tslint-eslint-rules` for `tslint`
[Issure](https://github.com/buzinas/tslint-eslint-rules/issues/392) about this open from 2020 😢

**Comment by timocov** [comment]
@SlicedSilver looks like it is finished already and can be closed?

**Comment by SlicedSilver** [comment]
> @SlicedSilver looks like it is finished already and can be closed?
Thanks :)
